Learn 50 implement sql database
lerow12/learning-game-analytics-backend pull request #8
Opened 2022-10-12 04:39 UTC by G33kabyt3

Review for table creation.

2022-10-12 04:39 UTC, G33kabyt3 commented
Gah forgot to lint

2022-10-18 23:00 UTC, G33kabyt3 commented
Yeah the tests aren't going to work. We need the mysql connector library as well a a working database engine. You can test them locally, but otherwise it's gonna be a pain.

2022-10-19 20:39 UTC, lerow12 requested changes
Just remove test for now since it doesn't really test much to merge this PR

2022-10-20 01:54 UTC, lerow12 approved these changes

2022-10-20 01:54 UTC, merged